package timesyncd

import (
	"fmt"
	"github.com/godbus/dbus/v5"
	"github.com/godbus/dbus/v5/introspect"
	"github.com/godbus/dbus/v5/prop"
	"os"
	"strings"

	logging "github.com/home-assistant/os-agent/utils/log"
)

const (
	objectPath    = "/io/hass/os/Config/Timesyncd"
	ifaceName     = "io.hass.os.Config.Timesyncd"
	timesyncdConf = "/etc/systemd/timesyncd.conf.d/50-os-agent.conf"
)

var (
	optNTPServer         []string
	optFallbackNTPServer []string
)

type timesyncd struct {
	conn  *dbus.Conn
	props *prop.Properties
}

func setNTPServer(c *prop.Change) *dbus.Error {
	servers, ok := c.Value.([]string)
	if !ok {
		return dbus.MakeFailedError(fmt.Errorf("invalid type for NTPServer"))
	}

	if err := writeTimesyncdConfig(servers, optFallbackNTPServer); err != nil {
		return dbus.MakeFailedError(err)
	}

	optNTPServer = servers
	return nil
}

func setFallbackNTPServer(c *prop.Change) *dbus.Error {
	servers, ok := c.Value.([]string)
	if !ok {
		return dbus.MakeFailedError(fmt.Errorf("invalid type for FallbackNTPServer"))
	}

	if err := writeTimesyncdConfig(optNTPServer, servers); err != nil {
		return dbus.MakeFailedError(err)
	}

	optFallbackNTPServer = servers
	return nil
}

// readTimesyncdConfig returns the NTP and FallbackNTP server lists from the
// drop-in file. A missing file yields two empty lists.
func readTimesyncdConfig() (ntp []string, fallbackNTP []string) {
	content, err := os.ReadFile(timesyncdConf)
	if err != nil {
		return nil, nil
	}

	for _, line := range strings.Split(string(content), "\n") {
		line = strings.TrimSpace(line)
		if value, found := strings.CutPrefix(line, "NTP="); found {
			ntp = strings.Fields(value)
		} else if value, found := strings.CutPrefix(line, "FallbackNTP="); found {
			fallbackNTP = strings.Fields(value)
		}
	}

	return ntp, fallbackNTP
}

// writeTimesyncdConfig renders the whole drop-in file from the server lists.
// Both lists empty removes the file so timesyncd falls back to its defaults.
func writeTimesyncdConfig(ntp []string, fallbackNTP []string) error {
	if len(ntp) == 0 && len(fallbackNTP) == 0 {
		if err := os.Remove(timesyncdConf); err != nil && !os.IsNotExist(err) {
			return fmt.Errorf("failed to remove %s: %w", timesyncdConf, err)
		}
		return nil
	}

	var b strings.Builder
	b.WriteString("# Generated by os-agent, do not edit.\n[Time]\n")
	if len(ntp) > 0 {
		fmt.Fprintf(&b, "NTP=%s\n", strings.Join(ntp, " "))
	}
	if len(fallbackNTP) > 0 {
		fmt.Fprintf(&b, "FallbackNTP=%s\n", strings.Join(fallbackNTP, " "))
	}

	if err := os.WriteFile(timesyncdConf, []byte(b.String()), 0644); err != nil { //nolint:gosec
		return fmt.Errorf("failed to write %s: %w", timesyncdConf, err)
	}

	return nil
}

func InitializeDBus(conn *dbus.Conn) {
	d := timesyncd{
		conn: conn,
	}

	optNTPServer, optFallbackNTPServer = readTimesyncdConfig()

	propsSpec := map[string]map[string]*prop.Prop{
		ifaceName: {
			"NTPServer": {
				Value:    optNTPServer,
				Writable: true,
				Emit:     prop.EmitTrue,
				Callback: setNTPServer,
			},
			"FallbackNTPServer": {
				Value:    optFallbackNTPServer,
				Writable: true,
				Emit:     prop.EmitTrue,
				Callback: setFallbackNTPServer,
			},
		},
	}

	props, err := prop.Export(conn, objectPath, propsSpec)
	if err != nil {
		logging.Critical.Panic(err)
	}
	d.props = props

	err = conn.Export(d, objectPath, ifaceName)
	if err != nil {
		logging.Critical.Panic(err)
	}

	node := &introspect.Node{
		Name: objectPath,
		Interfaces: []introspect.Interface{
			introspect.IntrospectData,
			prop.IntrospectData,
			{
				Name:       ifaceName,
				Methods:    introspect.Methods(d),
				Properties: props.Introspection(ifaceName),
			},
		},
	}

	err = conn.Export(introspect.NewIntrospectable(node), objectPath, "org.freedesktop.DBus.Introspectable")
	if err != nil {
		logging.Critical.Panic(err)
	}

	logging.Info.Printf("Exposing object %s with interface %s ...", objectPath, ifaceName)
}
